// <auto-generated />
using System;
using API.Chats.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Chats.Infrastructure.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Chats.Domain.Aggregates.Chat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AIEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ChatName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGroupChat")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("chat", (string)null);
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.ChatAgent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgentUsername")
                        .IsUnique();

                    b.ToTable("chat_agent", (string)null);
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.ChatFeature", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UserRestrictionsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FeatureName")
                        .IsUnique();

                    b.ToTable("chat_feature", (string)null);
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.FeatureRestrictedProfile", b =>
                {
                    b.Property<string>("RestrictedProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatFeatureId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RestrictedProfileId", "ChatFeatureId");

                    b.HasIndex("ChatFeatureId");

                    b.ToTable("feature_restricted_user", (string)null);
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.FeatureTestProfile", b =>
                {
                    b.Property<string>("TestProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatFeatureId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TestProfileId", "ChatFeatureId");

                    b.HasIndex("ChatFeatureId");

                    b.ToTable("feature_test_user", (string)null);
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<string>("ParticipantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("message", (string)null);
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.Participant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatAgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatNickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChatAgentId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("participant", (string)null);
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.UserProfilesAggregate.BlockedProfile", b =>
                {
                    b.Property<string>("BlockedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BlockedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BlockedById", "BlockedUserId");

                    b.HasIndex("BlockedUserId");

                    b.ToTable("blocked_profile", (string)null);
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.UserProfilesAggregate.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockedOut")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Suspended")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profile", (string)null);
                });

            modelBuilder.Entity("API.Shared.Domain.Entities.InternalOutboxEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("internal_outbox", (string)null);
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.FeatureRestrictedProfile", b =>
                {
                    b.HasOne("API.Chats.Domain.Aggregates.ChatFeature", "ChatFeature")
                        .WithMany()
                        .HasForeignKey("ChatFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Chats.Domain.Aggregates.UserProfilesAggregate.UserProfile", "RestrictedProfile")
                        .WithMany()
                        .HasForeignKey("RestrictedProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatFeature");

                    b.Navigation("RestrictedProfile");
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.FeatureTestProfile", b =>
                {
                    b.HasOne("API.Chats.Domain.Aggregates.ChatFeature", "ChatFeature")
                        .WithMany()
                        .HasForeignKey("ChatFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Chats.Domain.Aggregates.UserProfilesAggregate.UserProfile", "TestProfile")
                        .WithMany()
                        .HasForeignKey("TestProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatFeature");

                    b.Navigation("TestProfile");
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.Message", b =>
                {
                    b.HasOne("API.Chats.Domain.Aggregates.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("API.Chats.Domain.Aggregates.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.Participant", b =>
                {
                    b.HasOne("API.Chats.Domain.Aggregates.ChatAgent", "ChatAgent")
                        .WithMany()
                        .HasForeignKey("ChatAgentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("API.Chats.Domain.Aggregates.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Chats.Domain.Aggregates.UserProfilesAggregate.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Chat");

                    b.Navigation("ChatAgent");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.UserProfilesAggregate.BlockedProfile", b =>
                {
                    b.HasOne("API.Chats.Domain.Aggregates.UserProfilesAggregate.UserProfile", "BlockedBy")
                        .WithMany("BlockedProfiles")
                        .HasForeignKey("BlockedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Chats.Domain.Aggregates.UserProfilesAggregate.UserProfile", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedBy");

                    b.Navigation("BlockedUser");
                });

            modelBuilder.Entity("API.Chats.Domain.Aggregates.UserProfilesAggregate.UserProfile", b =>
                {
                    b.Navigation("BlockedProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
