version: '3.4'

services:
    api.accounts:
        depends_on:
            - redis
            - sqlServer
            - rabbitmq
            - mongo
        networks:
            - polyqube
        image: ${DOCKER_REGISTRY-}apiaccounts
        build:
            context: .
            dockerfile: src/Services/Accounts/API.Accounts/Dockerfile

    api.gateway:
        networks:
            - polyqube
        image: ${DOCKER_REGISTRY-}apigateway
        build:
            context: .
            dockerfile: src/Gateways/MainGateway/API.Gateway/Dockerfile

    api.filestorage:
        depends_on:
            - redis
            - rabbitmq
            - mongo
        networks:
            - polyqube
        image: ${DOCKER_REGISTRY-}apifilestorage
        build:
            context: .
            dockerfile: src/Services/FileStorage/API.FileStorage/Dockerfile

    redis:
        networks:
            - polyqube
        container_name: "Redis"
        image: redis:7.4.2-alpine
        volumes:
            - redisData:/data
    
    redisinsight:
        networks:
            - polyqube
        container_name: "RedisInsight"
        image: redis/redisinsight:latest
        ports:
            - 5540:5540
        volumes:
            - redisinsightData:/data
    
    sqlServer:
        networks:
            - polyqube
        container_name: "SqlServer"
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=${DB_PASSWORD}
            - MSSQL_PID=Developer
        volumes:
            - sqlServerData:/var/opt/mssql

    grafana:
        networks:
            - polyqube
        container_name: "Grafana"
        image: grafana/otel-lgtm
        ports:
            - 9090:9090
            - 9010:3000
        expose:
            - "4317"
            - "4318"
        volumes:
            - grafanaData:/data
            #- ./config/prometheus.yaml:/otel-lgtm/prometheus.yaml:ro
            - ./config/loki-config.yaml:/otel-lgtm/loki-config.yaml:ro
        depends_on:
            - api.accounts
            - api.gateway

    minio:
        networks:
            - polyqube
        container_name: "Minio"
        image: minio/minio:latest
        ports:
            - 9101:9001
            - 9100:9000
        volumes:
            - minioData:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /data --console-address ":9001"

    rabbitmq:
        networks:
            - polyqube
        container_name: "RabbitMQ"
        image: rabbitmq:4-management-alpine
        ports:
            - 15672:15672
        expose:
            - "5672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        volumes:
            - rabbitmqData:/var/lib/rabbitmq

    mongo:
        image: mongo
        container_name: "MongoDB"
        networks:
            - polyqube
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        volumes:
            - mongoDataDb:/data/db
            - mongoDataConfig:/data/configdb
        expose:
            - "27017"

    mongo-express:
        image: mongo-express
        networks:
            - polyqube
        container_name: "MongoExpress"
        restart: always
        ports:
            - 8181:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/
            ME_CONFIG_BASICAUTH: false

    proxy:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        container_name: 'Proxy'
        networks:
            - polyqube
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - proxyData:/data
            - proxyLetEncrypt:/etc/letsencrypt

networks:
    polyqube:
volumes:
    redisData:
    redisinsightData:
    sqlServerData:
    grafanaData:
    minioData:
    rabbitmqData:
    mongoDataDb:
    mongoDataConfig:
    proxyData:
    proxyLetEncrypt:
