version: '3.4'

services:
    api.accounts:
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_URLS=http://+:8080
            - AuthValidationOptions__Authority=http://api.accounts:8080
            - CorsOptions__AllowedOrigins__0=http://localhost:8040
            - CorsOptions__AllowedOrigins__1=http://api.gateway:8040
            - RedisOptions__RedisHost=redis:6379
            - DatabaseOptions__ConnectionString=Server=sqlServer,1433;Database=PolyqubeAccounts;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
        ports:
            - "8080"
    api.gateway:
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:8040
            - ASPNETCORE_HTTP_PORTS=8040
            - ReverseProxy__Clusters__AccountsCluser__Destinations__destination1__Address=http://api.accounts:8080
        ports:
            - 8040:8040
    redis:
        ports:
            - "6379"
    sqlServer:
        ports:
            - "1433"
