// <auto-generated />
using System;
using API.Admin.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Admin.Infrastructure.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    partial class AdminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Admin.Domain.Aggregates.FeatureInfoAggregate.FeatureInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UserRestrictionsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("feature_infos", (string)null);
                });

            modelBuilder.Entity("API.Admin.Domain.Aggregates.FeatureInfoAggregate.FeatureInfo", b =>
                {
                    b.OwnsMany("API.Admin.Domain.Aggregates.FeatureInfoAggregate.RestrictedUser", "RestrictedUsers", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FeatureInfoId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("RestrictedUserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("FeatureInfoId");

                            b1.HasIndex("RestrictedUserId")
                                .IsUnique();

                            b1.ToTable("feature_restricted_users", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FeatureInfoId");
                        });

                    b.OwnsMany("API.Admin.Domain.Aggregates.FeatureInfoAggregate.TestUser", "TestUsers", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FeatureInfoId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("TestUserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("FeatureInfoId");

                            b1.HasIndex("TestUserId")
                                .IsUnique();

                            b1.ToTable("feature_test_users", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FeatureInfoId");
                        });

                    b.Navigation("RestrictedUsers");

                    b.Navigation("TestUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
